### ISSUE TITLE
round times

### ISSUE THREAD

**Issue by georgringer** [froemken/mysqlreport#46]
there is imo no benefit in having times like "0.0057640075683594" i suggest to round it to something like "0.005764". this improves also the readability

**Comment by froemken** [comment]
Hi Georg,

I have set the double precision to 8 in ext_tables.sql since years. I'm sure it has been worked, but as precision value in float/double definition is not official, it could be that max allowed precision will be used in newer DB versions.

For now I have added a new Event and a new EventListener to modify profile records after fetching from DB. Maybe I will make precision configurable in future, but for now it is hard-coded to 6: https://github.com/froemken/mysqlreport/pull/55

Thank you for testing mysqlreport

Stefan
